version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.27.0-20241204
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
      - VNC_PASSWORD=yourpassword   # Set the VNC password here
    ports:
      - "5900:5900"  # Expose VNC port to access the browser's UI

  edge:
    image: selenium/node-edge:4.27.0-20241204
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
      - VNC_PASSWORD=yourpassword   # Set the VNC password here
    ports:
      - "5901:5900"  # Expose VNC port for Edge

  firefox:
    image: selenium/node-firefox:4.27.0-20241204
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
      - VNC_PASSWORD=yourpassword   # Set the VNC password here
    ports:
      - "5902:5900"  # Expose VNC port for Firefox

  selenium-hub:
    image: selenium/hub:4.27.0-20241204
    container_name: selenium-hub
    environment:
      - SE_ENABLE_TRACING=false
    ports:
      - "4442:4442"  # Event bus communication
      - "4443:4443"  # Event bus communication
      - "4444:4444"  # Selenium Hub port for client connections
